#ifndef MUSICDEFINES_H_DEFINED
#define MUSICDEFINES_H_DEFINED

#define MUSIC_PATH_COMPLETE 0

#define MUSIC_PUSHING_ONWARDS 1

#define MUSIC_POSITIVE_FORCE 2

#define MUSIC_POTENTIAL_FOR_ANYTHING 3

#define MUSIC_PASSION_FOR_EXPLORING 4

#define MUSIC_PAUSE 5

#define MUSIC_PRESENTING_VVVVVV 6

#define MUSIC_PLENARY 7

#define MUSIC_PREDESTINED_FATE 8

#define MUSIC_ECROF_EVITISOP 9

#define MUSIC_POPULAR_POTPOURRI 10

#define MUSIC_PIPE_DREAM 11

#define MUSIC_PRESSURE_COOKER 12

#define MUSIC_PACED_ENERGY 13

#define MUSIC_PIERCING_THE_SKY 14

#define MUSIC_PREDESTINED_FATE_REMIX 15

#endif
